image: "rust:latest"

build:
  image: docker:stable
  # When using dind, it's wise to use the overlayfs driver for
  # improved performance.
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  before_script:
    - docker info
  script:
    - docker build .

check-format:
  script:
    - cargo fmt -- --check

lint-code:
  script:
    - cargo clippy -- -D warnings

pages:
  script:
    - apt-get update -yqq
    - apt-get install -yqq --no-install-recommends emacs org-mode texlive-latex-extra texlive-latex-base texlive-generic-recommended texlive-fonts-recommended
    - emacs -Q --batch README.org -f org-latex-export-to-pdf
    - curl -o /etc/emacs/htmlize.el https://raw.githubusercontent.com/hniksic/emacs-htmlize/master/htmlize.el
    - emacs -Q --batch README.org --eval "(load \"/etc/emacs/htmlize.el\")" -f org-html-export-to-html
    - mkdir public
    - mv README.html public/index.html
    - mv README.pdf public
  artifacts:
    paths:
      - README.pdf
      - public
