[package]
name = "tpm-openpgp"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tss-esapi = "5.1.0"
structopt = "0.3.22"
